services:
  workbench:
    networks:
      top-secret-edge:
        aliases:
          - workbench
          - workbench.top.secret

networks:
  top-secret-edge:
    external: true
    name: ${TOPSECRET_EDGE_NETWORK:-ki_infra_seu_test}
