server {
    listen 80;
    server_name workbench.top.secret wb.top.secret;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name workbench.top.secret wb.top.secret;

    client_max_body_size 1024M;

    include /etc/nginx/conf.d/snippets/ssl-top-secret.conf;

    location / {
        proxy_pass http://workbench:8088;
        proxy_read_timeout 3600s;
        proxy_connect_timeout 60s;
        proxy_send_timeout 3600s;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Port 443;
        include /etc/nginx/conf.d/snippets/proxy-common.conf;
    }
}
